### ISSUE TITLE
Home page must be on the root folder with name of index

### ISSUE THREAD

**Issue by 14Muhammad** [shehreen0217/Final-Project#1]
![screenshot_2](https://user-images.githubusercontent.com/14924671/48958903-cfbfae00-ef83-11e8-8621-8bd541a49cc5.jpg)

- Use proper commit messages.
- Remove IDE config folder .idea

**Comment by 14Muhammad** [comment]
@MuhammadAliSulehri I have removed .idea folder with the following steps.

### Steps to remove directory

1. git rm -r --cached FolderName
2. git commit -m "Removed folder from repository"
3. git push origin master

**Comment by 14Muhammad** [comment]
@MuhammadAliSulehri  Issue is closed. Good work 👍

**Comment by MuhammadAliSulehri** [comment]
i will observe the steps and will remove directories like this in the future 👍🏻 and thank you sir
